// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/internal/logic/permissionservice"
	"github.com/cy77cc/go-microstack/usercenter/rpc/internal/svc"
	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"
)

type PermissionServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPermissionServiceServer
}

func NewPermissionServiceServer(svcCtx *svc.ServiceContext) *PermissionServiceServer {
	return &PermissionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PermissionServiceServer) CreatePermission(ctx context.Context, in *pb.CreatePermissionReq) (*pb.PermissionResp, error) {
	l := permissionservicelogic.NewCreatePermissionLogic(ctx, s.svcCtx)
	return l.CreatePermission(in)
}

func (s *PermissionServiceServer) GetPermission(ctx context.Context, in *pb.GetPermissionReq) (*pb.PermissionResp, error) {
	l := permissionservicelogic.NewGetPermissionLogic(ctx, s.svcCtx)
	return l.GetPermission(in)
}

func (s *PermissionServiceServer) UpdatePermission(ctx context.Context, in *pb.UpdatePermissionReq) (*pb.PermissionResp, error) {
	l := permissionservicelogic.NewUpdatePermissionLogic(ctx, s.svcCtx)
	return l.UpdatePermission(in)
}

func (s *PermissionServiceServer) DeletePermission(ctx context.Context, in *pb.DeletePermissionReq) (*pb.LogoutResp, error) {
	l := permissionservicelogic.NewDeletePermissionLogic(ctx, s.svcCtx)
	return l.DeletePermission(in)
}

func (s *PermissionServiceServer) ListPermissions(ctx context.Context, in *pb.ListPermissionsReq) (*pb.ListPermissionsResp, error) {
	l := permissionservicelogic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}

func (s *PermissionServiceServer) CheckPermission(ctx context.Context, in *pb.CheckPermissionReq) (*pb.CheckPermissionResp, error) {
	l := permissionservicelogic.NewCheckPermissionLogic(ctx, s.svcCtx)
	return l.CheckPermission(in)
}
