// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package roleservice

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRoleReq           = pb.AssignRoleReq
	CheckPermissionReq      = pb.CheckPermissionReq
	CheckPermissionResp     = pb.CheckPermissionResp
	CreatePermissionReq     = pb.CreatePermissionReq
	CreateRoleReq           = pb.CreateRoleReq
	CreateUserReq           = pb.CreateUserReq
	DeletePermissionReq     = pb.DeletePermissionReq
	DeleteRoleReq           = pb.DeleteRoleReq
	DeleteUserReq           = pb.DeleteUserReq
	GetPermissionReq        = pb.GetPermissionReq
	GetRoleReq              = pb.GetRoleReq
	GetUserReq              = pb.GetUserReq
	GrantPermissionReq      = pb.GrantPermissionReq
	ListPermissionsReq      = pb.ListPermissionsReq
	ListPermissionsResp     = pb.ListPermissionsResp
	ListRolePermissionsReq  = pb.ListRolePermissionsReq
	ListRolePermissionsResp = pb.ListRolePermissionsResp
	ListRolesReq            = pb.ListRolesReq
	ListRolesResp           = pb.ListRolesResp
	ListUserRolesReq        = pb.ListUserRolesReq
	ListUserRolesResp       = pb.ListUserRolesResp
	ListUsersReq            = pb.ListUsersReq
	ListUsersResp           = pb.ListUsersResp
	LoginReq                = pb.LoginReq
	LoginResp               = pb.LoginResp
	LogoutReq               = pb.LogoutReq
	LogoutResp              = pb.LogoutResp
	Permission              = pb.Permission
	PermissionResp          = pb.PermissionResp
	RefreshTokenReq         = pb.RefreshTokenReq
	RevokePermissionReq     = pb.RevokePermissionReq
	RevokeRoleReq           = pb.RevokeRoleReq
	Role                    = pb.Role
	RoleResp                = pb.RoleResp
	UpdatePermissionReq     = pb.UpdatePermissionReq
	UpdateRoleReq           = pb.UpdateRoleReq
	UpdateUserReq           = pb.UpdateUserReq
	User                    = pb.User
	UserResp                = pb.UserResp
	VerifyTokenReq          = pb.VerifyTokenReq
	VerifyTokenResp         = pb.VerifyTokenResp

	RoleService interface {
		CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*RoleResp, error)
		GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*RoleResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*RoleResp, error)
		DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*LogoutResp, error)
		ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error)
		GrantPermissionToRole(ctx context.Context, in *GrantPermissionReq, opts ...grpc.CallOption) (*LogoutResp, error)
		RevokePermissionFromRole(ctx context.Context, in *RevokePermissionReq, opts ...grpc.CallOption) (*LogoutResp, error)
		ListRolePermissions(ctx context.Context, in *ListRolePermissionsReq, opts ...grpc.CallOption) (*ListRolePermissionsResp, error)
	}

	defaultRoleService struct {
		cli zrpc.Client
	}
)

func NewRoleService(cli zrpc.Client) RoleService {
	return &defaultRoleService{
		cli: cli,
	}
}

func (m *defaultRoleService) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*RoleResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultRoleService) GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*RoleResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultRoleService) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*RoleResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRoleService) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRoleService) ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.ListRoles(ctx, in, opts...)
}

func (m *defaultRoleService) GrantPermissionToRole(ctx context.Context, in *GrantPermissionReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.GrantPermissionToRole(ctx, in, opts...)
}

func (m *defaultRoleService) RevokePermissionFromRole(ctx context.Context, in *RevokePermissionReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.RevokePermissionFromRole(ctx, in, opts...)
}

func (m *defaultRoleService) ListRolePermissions(ctx context.Context, in *ListRolePermissionsReq, opts ...grpc.CallOption) (*ListRolePermissionsResp, error) {
	client := pb.NewRoleServiceClient(m.cli.Conn())
	return client.ListRolePermissions(ctx, in, opts...)
}
