// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: fileserver.proto

package server

import (
	"context"

	"github.com/cy77cc/go-microstack/fileserver/rpc/internal/logic"
	"github.com/cy77cc/go-microstack/fileserver/rpc/internal/svc"
	"github.com/cy77cc/go-microstack/fileserver/rpc/pb"
)

type FileserverServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileserverServer
}

func NewFileserverServer(svcCtx *svc.ServiceContext) *FileserverServer {
	return &FileserverServer{
		svcCtx: svcCtx,
	}
}

func (s *FileserverServer) CreateBucket(ctx context.Context, in *pb.CreateBucketReq) (*pb.CreateBucketResp, error) {
	l := logic.NewCreateBucketLogic(ctx, s.svcCtx)
	return l.CreateBucket(in)
}

func (s *FileserverServer) Upload(ctx context.Context, in *pb.UploadReq) (*pb.UploadResp, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

func (s *FileserverServer) Download(ctx context.Context, in *pb.DownloadReq) (*pb.DownloadResp, error) {
	l := logic.NewDownloadLogic(ctx, s.svcCtx)
	return l.Download(in)
}

func (s *FileserverServer) InitiateMultipartUpload(ctx context.Context, in *pb.InitiateMultipartUploadReq) (*pb.InitiateMultipartUploadResp, error) {
	l := logic.NewInitiateMultipartUploadLogic(ctx, s.svcCtx)
	return l.InitiateMultipartUpload(in)
}

func (s *FileserverServer) UploadPart(ctx context.Context, in *pb.UploadPartReq) (*pb.UploadPartResp, error) {
	l := logic.NewUploadPartLogic(ctx, s.svcCtx)
	return l.UploadPart(in)
}

func (s *FileserverServer) CompleteMultipartUpload(ctx context.Context, in *pb.CompleteMultipartUploadReq) (*pb.CompleteMultipartUploadResp, error) {
	l := logic.NewCompleteMultipartUploadLogic(ctx, s.svcCtx)
	return l.CompleteMultipartUpload(in)
}

func (s *FileserverServer) AbortMultipartUpload(ctx context.Context, in *pb.AbortMultipartUploadReq) (*pb.AbortMultipartUploadResp, error) {
	l := logic.NewAbortMultipartUploadLogic(ctx, s.svcCtx)
	return l.AbortMultipartUpload(in)
}

func (s *FileserverServer) GetFileMeta(ctx context.Context, in *pb.GetFileMetaReq) (*pb.GetFileMetaResp, error) {
	l := logic.NewGetFileMetaLogic(ctx, s.svcCtx)
	return l.GetFileMeta(in)
}

func (s *FileserverServer) GetFileUrl(ctx context.Context, in *pb.GetFileUrlReq) (*pb.GetFileUrlResp, error) {
	l := logic.NewGetFileUrlLogic(ctx, s.svcCtx)
	return l.GetFileUrl(in)
}
