// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	buckets "github.com/cy77cc/go-microstack/fileserver/api/internal/handler/buckets"
	files "github.com/cy77cc/go-microstack/fileserver/api/internal/handler/files"
	uploads "github.com/cy77cc/go-microstack/fileserver/api/internal/handler/uploads"
	"github.com/cy77cc/go-microstack/fileserver/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: GetHealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					// 创建存储桶
					Method:  http.MethodPost,
					Path:    "/buckets",
					Handler: buckets.CreateBucketHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/fileserver/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					// 单文件上传
					Method:  http.MethodPost,
					Path:    "/files",
					Handler: files.UploadFileHandler(serverCtx),
				},
				{
					// 获取文件元数据
					Method:  http.MethodGet,
					Path:    "/files/:fileId/meta",
					Handler: files.GetFileMetaHandler(serverCtx),
				},
				{
					// 获取文件下载链接
					Method:  http.MethodGet,
					Path:    "/files/:fileId/url",
					Handler: files.GetDownloadUrlHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/fileserver/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					// 初始化分片上传
					Method:  http.MethodPost,
					Path:    "/uploads",
					Handler: uploads.InitiateMultipartUploadHandler(serverCtx),
				},
				{
					// 终止分片上传
					Method:  http.MethodDelete,
					Path:    "/uploads/:uploadId",
					Handler: uploads.AbortMultipartUploadHandler(serverCtx),
				},
				{
					// 完成分片上传
					Method:  http.MethodPost,
					Path:    "/uploads/:uploadId/complete",
					Handler: uploads.CompleteMultipartUploadHandler(serverCtx),
				},
				{
					// 上传分片
					Method:  http.MethodPut,
					Path:    "/uploads/:uploadId/parts/:partNumber",
					Handler: uploads.UploadPartHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/fileserver/v1"),
	)
}
