// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package userservice

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRoleReq           = pb.AssignRoleReq
	CheckPermissionReq      = pb.CheckPermissionReq
	CheckPermissionResp     = pb.CheckPermissionResp
	CreatePermissionReq     = pb.CreatePermissionReq
	CreateRoleReq           = pb.CreateRoleReq
	CreateUserReq           = pb.CreateUserReq
	DeletePermissionReq     = pb.DeletePermissionReq
	DeleteRoleReq           = pb.DeleteRoleReq
	DeleteUserReq           = pb.DeleteUserReq
	GetPermissionReq        = pb.GetPermissionReq
	GetRoleReq              = pb.GetRoleReq
	GetUserReq              = pb.GetUserReq
	GrantPermissionReq      = pb.GrantPermissionReq
	ListPermissionsReq      = pb.ListPermissionsReq
	ListPermissionsResp     = pb.ListPermissionsResp
	ListRolePermissionsReq  = pb.ListRolePermissionsReq
	ListRolePermissionsResp = pb.ListRolePermissionsResp
	ListRolesReq            = pb.ListRolesReq
	ListRolesResp           = pb.ListRolesResp
	ListUserRolesReq        = pb.ListUserRolesReq
	ListUserRolesResp       = pb.ListUserRolesResp
	ListUsersReq            = pb.ListUsersReq
	ListUsersResp           = pb.ListUsersResp
	LoginReq                = pb.LoginReq
	LoginResp               = pb.LoginResp
	LogoutReq               = pb.LogoutReq
	LogoutResp              = pb.LogoutResp
	Permission              = pb.Permission
	PermissionResp          = pb.PermissionResp
	RefreshTokenReq         = pb.RefreshTokenReq
	RevokePermissionReq     = pb.RevokePermissionReq
	RevokeRoleReq           = pb.RevokeRoleReq
	Role                    = pb.Role
	RoleResp                = pb.RoleResp
	UpdatePermissionReq     = pb.UpdatePermissionReq
	UpdateRoleReq           = pb.UpdateRoleReq
	UpdateUserReq           = pb.UpdateUserReq
	User                    = pb.User
	UserResp                = pb.UserResp
	VerifyTokenReq          = pb.VerifyTokenReq
	VerifyTokenResp         = pb.VerifyTokenResp

	UserService interface {
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*UserResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UserResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*LogoutResp, error)
		ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
		AssignRoleToUser(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*LogoutResp, error)
		RevokeRoleFromUser(ctx context.Context, in *RevokeRoleReq, opts ...grpc.CallOption) (*LogoutResp, error)
		ListUserRoles(ctx context.Context, in *ListUserRolesReq, opts ...grpc.CallOption) (*ListUserRolesResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUserService) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUserService) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

func (m *defaultUserService) AssignRoleToUser(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.AssignRoleToUser(ctx, in, opts...)
}

func (m *defaultUserService) RevokeRoleFromUser(ctx context.Context, in *RevokeRoleReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.RevokeRoleFromUser(ctx, in, opts...)
}

func (m *defaultUserService) ListUserRoles(ctx context.Context, in *ListUserRolesReq, opts ...grpc.CallOption) (*ListUserRolesResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ListUserRoles(ctx, in, opts...)
}
