// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authRefreshTokensFieldNames          = builder.RawFieldNames(&AuthRefreshTokens{})
	authRefreshTokensRows                = strings.Join(authRefreshTokensFieldNames, ",")
	authRefreshTokensRowsExpectAutoSet   = strings.Join(stringx.Remove(authRefreshTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authRefreshTokensRowsWithPlaceHolder = strings.Join(stringx.Remove(authRefreshTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthRefreshTokensIdPrefix = "cache:authRefreshTokens:id:"
)

type (
	authRefreshTokensModel interface {
		Insert(ctx context.Context, data *AuthRefreshTokens) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthRefreshTokens, error)
		Update(ctx context.Context, data *AuthRefreshTokens) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthRefreshTokensModel struct {
		sqlc.CachedConn
		table string
	}

	AuthRefreshTokens struct {
		Id         uint64 `db:"id"`
		UserId     uint64 `db:"user_id"`
		Token      string `db:"token"`
		Expires    int64  `db:"expires"`
		Revoked    int64  `db:"revoked"`
		CreateTime int64  `db:"create_time"`
	}
)

func newAuthRefreshTokensModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthRefreshTokensModel {
	return &defaultAuthRefreshTokensModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_refresh_tokens`",
	}
}

func (m *defaultAuthRefreshTokensModel) Delete(ctx context.Context, id uint64) error {
	authRefreshTokensIdKey := fmt.Sprintf("%s%v", cacheAuthRefreshTokensIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authRefreshTokensIdKey)
	return err
}

func (m *defaultAuthRefreshTokensModel) FindOne(ctx context.Context, id uint64) (*AuthRefreshTokens, error) {
	authRefreshTokensIdKey := fmt.Sprintf("%s%v", cacheAuthRefreshTokensIdPrefix, id)
	var resp AuthRefreshTokens
	err := m.QueryRowCtx(ctx, &resp, authRefreshTokensIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authRefreshTokensRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthRefreshTokensModel) Insert(ctx context.Context, data *AuthRefreshTokens) (sql.Result, error) {
	authRefreshTokensIdKey := fmt.Sprintf("%s%v", cacheAuthRefreshTokensIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, authRefreshTokensRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Token, data.Expires, data.Revoked)
	}, authRefreshTokensIdKey)
	return ret, err
}

func (m *defaultAuthRefreshTokensModel) Update(ctx context.Context, data *AuthRefreshTokens) error {
	authRefreshTokensIdKey := fmt.Sprintf("%s%v", cacheAuthRefreshTokensIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authRefreshTokensRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Token, data.Expires, data.Revoked, data.Id)
	}, authRefreshTokensIdKey)
	return err
}

func (m *defaultAuthRefreshTokensModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthRefreshTokensIdPrefix, primary)
}

func (m *defaultAuthRefreshTokensModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authRefreshTokensRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthRefreshTokensModel) tableName() string {
	return m.table
}
