// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	permissionsFieldNames          = builder.RawFieldNames(&Permissions{})
	permissionsRows                = strings.Join(permissionsFieldNames, ",")
	permissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(permissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	permissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(permissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePermissionsIdPrefix   = "cache:permissions:id:"
	cachePermissionsCodePrefix = "cache:permissions:code:"
)

type (
	permissionsModel interface {
		Insert(ctx context.Context, data *Permissions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Permissions, error)
		FindOneByCode(ctx context.Context, code string) (*Permissions, error)
		Update(ctx context.Context, data *Permissions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPermissionsModel struct {
		sqlc.CachedConn
		table string
	}

	Permissions struct {
		Id          uint64 `db:"id"`
		Name        string `db:"name"`
		Code        string `db:"code"`
		Type        int64  `db:"type"`
		Resource    string `db:"resource"`
		Action      string `db:"action"`
		Description string `db:"description"`
		Status      int64  `db:"status"`
		CreateTime  int64  `db:"create_time"`
		UpdateTime  int64  `db:"update_time"`
	}
)

func newPermissionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPermissionsModel {
	return &defaultPermissionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`permissions`",
	}
}

func (m *defaultPermissionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	permissionsCodeKey := fmt.Sprintf("%s%v", cachePermissionsCodePrefix, data.Code)
	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, permissionsCodeKey, permissionsIdKey)
	return err
}

func (m *defaultPermissionsModel) FindOne(ctx context.Context, id uint64) (*Permissions, error) {
	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, id)
	var resp Permissions
	err := m.QueryRowCtx(ctx, &resp, permissionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionsModel) FindOneByCode(ctx context.Context, code string) (*Permissions, error) {
	permissionsCodeKey := fmt.Sprintf("%s%v", cachePermissionsCodePrefix, code)
	var resp Permissions
	err := m.QueryRowIndexCtx(ctx, &resp, permissionsCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", permissionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionsModel) Insert(ctx context.Context, data *Permissions) (sql.Result, error) {
	permissionsCodeKey := fmt.Sprintf("%s%v", cachePermissionsCodePrefix, data.Code)
	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, permissionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Code, data.Type, data.Resource, data.Action, data.Description, data.Status)
	}, permissionsCodeKey, permissionsIdKey)
	return ret, err
}

func (m *defaultPermissionsModel) Update(ctx context.Context, newData *Permissions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	permissionsCodeKey := fmt.Sprintf("%s%v", cachePermissionsCodePrefix, data.Code)
	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, permissionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Type, newData.Resource, newData.Action, newData.Description, newData.Status, newData.Id)
	}, permissionsCodeKey, permissionsIdKey)
	return err
}

func (m *defaultPermissionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePermissionsIdPrefix, primary)
}

func (m *defaultPermissionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPermissionsModel) tableName() string {
	return m.table
}
