// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolePermissionsFieldNames          = builder.RawFieldNames(&RolePermissions{})
	rolePermissionsRows                = strings.Join(rolePermissionsFieldNames, ",")
	rolePermissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(rolePermissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rolePermissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(rolePermissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRolePermissionsIdPrefix                 = "cache:rolePermissions:id:"
	cacheRolePermissionsRoleIdPermissionIdPrefix = "cache:rolePermissions:roleId:permissionId:"
)

type (
	rolePermissionsModel interface {
		Insert(ctx context.Context, data *RolePermissions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*RolePermissions, error)
		FindOneByRoleIdPermissionId(ctx context.Context, roleId uint64, permissionId uint64) (*RolePermissions, error)
		Update(ctx context.Context, data *RolePermissions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRolePermissionsModel struct {
		sqlc.CachedConn
		table string
	}

	RolePermissions struct {
		Id           uint64 `db:"id"`
		RoleId       uint64 `db:"role_id"`
		PermissionId uint64 `db:"permission_id"`
	}
)

func newRolePermissionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRolePermissionsModel {
	return &defaultRolePermissionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`role_permissions`",
	}
}

func (m *defaultRolePermissionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rolePermissionsIdKey := fmt.Sprintf("%s%v", cacheRolePermissionsIdPrefix, id)
	rolePermissionsRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionsRoleIdPermissionIdPrefix, data.RoleId, data.PermissionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rolePermissionsIdKey, rolePermissionsRoleIdPermissionIdKey)
	return err
}

func (m *defaultRolePermissionsModel) FindOne(ctx context.Context, id uint64) (*RolePermissions, error) {
	rolePermissionsIdKey := fmt.Sprintf("%s%v", cacheRolePermissionsIdPrefix, id)
	var resp RolePermissions
	err := m.QueryRowCtx(ctx, &resp, rolePermissionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolePermissionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolePermissionsModel) FindOneByRoleIdPermissionId(ctx context.Context, roleId uint64, permissionId uint64) (*RolePermissions, error) {
	rolePermissionsRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionsRoleIdPermissionIdPrefix, roleId, permissionId)
	var resp RolePermissions
	err := m.QueryRowIndexCtx(ctx, &resp, rolePermissionsRoleIdPermissionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? and `permission_id` = ? limit 1", rolePermissionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roleId, permissionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolePermissionsModel) Insert(ctx context.Context, data *RolePermissions) (sql.Result, error) {
	rolePermissionsIdKey := fmt.Sprintf("%s%v", cacheRolePermissionsIdPrefix, data.Id)
	rolePermissionsRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionsRoleIdPermissionIdPrefix, data.RoleId, data.PermissionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, rolePermissionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	}, rolePermissionsIdKey, rolePermissionsRoleIdPermissionIdKey)
	return ret, err
}

func (m *defaultRolePermissionsModel) Update(ctx context.Context, newData *RolePermissions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rolePermissionsIdKey := fmt.Sprintf("%s%v", cacheRolePermissionsIdPrefix, data.Id)
	rolePermissionsRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionsRoleIdPermissionIdPrefix, data.RoleId, data.PermissionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rolePermissionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RoleId, newData.PermissionId, newData.Id)
	}, rolePermissionsIdKey, rolePermissionsRoleIdPermissionIdKey)
	return err
}

func (m *defaultRolePermissionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRolePermissionsIdPrefix, primary)
}

func (m *defaultRolePermissionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolePermissionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRolePermissionsModel) tableName() string {
	return m.table
}
