// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolesFieldNames          = builder.RawFieldNames(&Roles{})
	rolesRows                = strings.Join(rolesFieldNames, ",")
	rolesRowsExpectAutoSet   = strings.Join(stringx.Remove(rolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rolesRowsWithPlaceHolder = strings.Join(stringx.Remove(rolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRolesIdPrefix   = "cache:roles:id:"
	cacheRolesCodePrefix = "cache:roles:code:"
)

type (
	rolesModel interface {
		Insert(ctx context.Context, data *Roles) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Roles, error)
		FindOneByCode(ctx context.Context, code string) (*Roles, error)
		Update(ctx context.Context, data *Roles) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRolesModel struct {
		sqlc.CachedConn
		table string
	}

	Roles struct {
		Id          uint64 `db:"id"`
		Name        string `db:"name"`
		Code        string `db:"code"`
		Description string `db:"description"`
		Status      int64  `db:"status"`
		CreateTime  int64  `db:"create_time"`
		UpdateTime  int64  `db:"update_time"`
	}
)

func newRolesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRolesModel {
	return &defaultRolesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`roles`",
	}
}

func (m *defaultRolesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rolesCodeKey := fmt.Sprintf("%s%v", cacheRolesCodePrefix, data.Code)
	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rolesCodeKey, rolesIdKey)
	return err
}

func (m *defaultRolesModel) FindOne(ctx context.Context, id uint64) (*Roles, error) {
	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, id)
	var resp Roles
	err := m.QueryRowCtx(ctx, &resp, rolesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) FindOneByCode(ctx context.Context, code string) (*Roles, error) {
	rolesCodeKey := fmt.Sprintf("%s%v", cacheRolesCodePrefix, code)
	var resp Roles
	err := m.QueryRowIndexCtx(ctx, &resp, rolesCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", rolesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) Insert(ctx context.Context, data *Roles) (sql.Result, error) {
	rolesCodeKey := fmt.Sprintf("%s%v", cacheRolesCodePrefix, data.Code)
	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, rolesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Code, data.Description, data.Status)
	}, rolesCodeKey, rolesIdKey)
	return ret, err
}

func (m *defaultRolesModel) Update(ctx context.Context, newData *Roles) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rolesCodeKey := fmt.Sprintf("%s%v", cacheRolesCodePrefix, data.Code)
	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rolesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Description, newData.Status, newData.Id)
	}, rolesCodeKey, rolesIdKey)
	return err
}

func (m *defaultRolesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRolesIdPrefix, primary)
}

func (m *defaultRolesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRolesModel) tableName() string {
	return m.table
}
