// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/internal/logic/roleservice"
	"github.com/cy77cc/go-microstack/usercenter/rpc/internal/svc"
	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServiceServer) CreateRole(ctx context.Context, in *pb.CreateRoleReq) (*pb.RoleResp, error) {
	l := roleservicelogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *RoleServiceServer) GetRole(ctx context.Context, in *pb.GetRoleReq) (*pb.RoleResp, error) {
	l := roleservicelogic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

func (s *RoleServiceServer) UpdateRole(ctx context.Context, in *pb.UpdateRoleReq) (*pb.RoleResp, error) {
	l := roleservicelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *RoleServiceServer) DeleteRole(ctx context.Context, in *pb.DeleteRoleReq) (*pb.LogoutResp, error) {
	l := roleservicelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *RoleServiceServer) ListRoles(ctx context.Context, in *pb.ListRolesReq) (*pb.ListRolesResp, error) {
	l := roleservicelogic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

func (s *RoleServiceServer) GrantPermissionToRole(ctx context.Context, in *pb.GrantPermissionReq) (*pb.LogoutResp, error) {
	l := roleservicelogic.NewGrantPermissionToRoleLogic(ctx, s.svcCtx)
	return l.GrantPermissionToRole(in)
}

func (s *RoleServiceServer) RevokePermissionFromRole(ctx context.Context, in *pb.RevokePermissionReq) (*pb.LogoutResp, error) {
	l := roleservicelogic.NewRevokePermissionFromRoleLogic(ctx, s.svcCtx)
	return l.RevokePermissionFromRole(in)
}

func (s *RoleServiceServer) ListRolePermissions(ctx context.Context, in *pb.ListRolePermissionsReq) (*pb.ListRolePermissionsResp, error) {
	l := roleservicelogic.NewListRolePermissionsLogic(ctx, s.svcCtx)
	return l.ListRolePermissions(in)
}
