// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bucketConfigFieldNames          = builder.RawFieldNames(&BucketConfig{})
	bucketConfigRows                = strings.Join(bucketConfigFieldNames, ",")
	bucketConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(bucketConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bucketConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(bucketConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBucketConfigIdPrefix     = "cache:bucketConfig:id:"
	cacheBucketConfigBucketPrefix = "cache:bucketConfig:bucket:"
)

type (
	bucketConfigModel interface {
		Insert(ctx context.Context, data *BucketConfig) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*BucketConfig, error)
		FindOneByBucket(ctx context.Context, bucket string) (*BucketConfig, error)
		Update(ctx context.Context, data *BucketConfig) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultBucketConfigModel struct {
		sqlc.CachedConn
		table string
	}

	BucketConfig struct {
		Id          uint64 `db:"id"`           // 主键ID
		Bucket      string `db:"bucket"`       // 存储桶
		StorageType int64  `db:"storage_type"` // 存储类型(1=MINIO,2=LOCAL)
		Endpoint    string `db:"endpoint"`     // 存储端点
		Region      string `db:"region"`       // 区域
		IsPublic    int64  `db:"is_public"`    // 是否公有读
	}
)

func newBucketConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBucketConfigModel {
	return &defaultBucketConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`bucket_config`",
	}
}

func (m *defaultBucketConfigModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	bucketConfigBucketKey := fmt.Sprintf("%s%v", cacheBucketConfigBucketPrefix, data.Bucket)
	bucketConfigIdKey := fmt.Sprintf("%s%v", cacheBucketConfigIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, bucketConfigBucketKey, bucketConfigIdKey)
	return err
}

func (m *defaultBucketConfigModel) FindOne(ctx context.Context, id uint64) (*BucketConfig, error) {
	bucketConfigIdKey := fmt.Sprintf("%s%v", cacheBucketConfigIdPrefix, id)
	var resp BucketConfig
	err := m.QueryRowCtx(ctx, &resp, bucketConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bucketConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBucketConfigModel) FindOneByBucket(ctx context.Context, bucket string) (*BucketConfig, error) {
	bucketConfigBucketKey := fmt.Sprintf("%s%v", cacheBucketConfigBucketPrefix, bucket)
	var resp BucketConfig
	err := m.QueryRowIndexCtx(ctx, &resp, bucketConfigBucketKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `bucket` = ? limit 1", bucketConfigRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, bucket); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBucketConfigModel) Insert(ctx context.Context, data *BucketConfig) (sql.Result, error) {
	bucketConfigBucketKey := fmt.Sprintf("%s%v", cacheBucketConfigBucketPrefix, data.Bucket)
	bucketConfigIdKey := fmt.Sprintf("%s%v", cacheBucketConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, bucketConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Bucket, data.StorageType, data.Endpoint, data.Region, data.IsPublic)
	}, bucketConfigBucketKey, bucketConfigIdKey)
	return ret, err
}

func (m *defaultBucketConfigModel) Update(ctx context.Context, newData *BucketConfig) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	bucketConfigBucketKey := fmt.Sprintf("%s%v", cacheBucketConfigBucketPrefix, data.Bucket)
	bucketConfigIdKey := fmt.Sprintf("%s%v", cacheBucketConfigIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bucketConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Bucket, newData.StorageType, newData.Endpoint, newData.Region, newData.IsPublic, newData.Id)
	}, bucketConfigBucketKey, bucketConfigIdKey)
	return err
}

func (m *defaultBucketConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBucketConfigIdPrefix, primary)
}

func (m *defaultBucketConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bucketConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBucketConfigModel) tableName() string {
	return m.table
}
