// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	multipartPartFieldNames          = builder.RawFieldNames(&MultipartPart{})
	multipartPartRows                = strings.Join(multipartPartFieldNames, ",")
	multipartPartRowsExpectAutoSet   = strings.Join(stringx.Remove(multipartPartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	multipartPartRowsWithPlaceHolder = strings.Join(stringx.Remove(multipartPartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMultipartPartIdPrefix                 = "cache:multipartPart:id:"
	cacheMultipartPartUploadIdPartNumberPrefix = "cache:multipartPart:uploadId:partNumber:"
)

type (
	multipartPartModel interface {
		Insert(ctx context.Context, data *MultipartPart) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MultipartPart, error)
		FindOneByUploadIdPartNumber(ctx context.Context, uploadId string, partNumber int64) (*MultipartPart, error)
		Update(ctx context.Context, data *MultipartPart) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMultipartPartModel struct {
		sqlc.CachedConn
		table string
	}

	MultipartPart struct {
		Id         uint64 `db:"id"`          // 主键ID
		UploadId   string `db:"upload_id"`   // 分片上传ID
		PartNumber int64  `db:"part_number"` // 分片序号
		Etag       string `db:"etag"`        // ETag
		Size       int64  `db:"size"`        // 分片大小
		CreateTime int64  `db:"create_time"` // 创建时间
	}
)

func newMultipartPartModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMultipartPartModel {
	return &defaultMultipartPartModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`multipart_part`",
	}
}

func (m *defaultMultipartPartModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	multipartPartIdKey := fmt.Sprintf("%s%v", cacheMultipartPartIdPrefix, id)
	multipartPartUploadIdPartNumberKey := fmt.Sprintf("%s%v:%v", cacheMultipartPartUploadIdPartNumberPrefix, data.UploadId, data.PartNumber)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, multipartPartIdKey, multipartPartUploadIdPartNumberKey)
	return err
}

func (m *defaultMultipartPartModel) FindOne(ctx context.Context, id uint64) (*MultipartPart, error) {
	multipartPartIdKey := fmt.Sprintf("%s%v", cacheMultipartPartIdPrefix, id)
	var resp MultipartPart
	err := m.QueryRowCtx(ctx, &resp, multipartPartIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", multipartPartRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMultipartPartModel) FindOneByUploadIdPartNumber(ctx context.Context, uploadId string, partNumber int64) (*MultipartPart, error) {
	multipartPartUploadIdPartNumberKey := fmt.Sprintf("%s%v:%v", cacheMultipartPartUploadIdPartNumberPrefix, uploadId, partNumber)
	var resp MultipartPart
	err := m.QueryRowIndexCtx(ctx, &resp, multipartPartUploadIdPartNumberKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `upload_id` = ? and `part_number` = ? limit 1", multipartPartRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uploadId, partNumber); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMultipartPartModel) Insert(ctx context.Context, data *MultipartPart) (sql.Result, error) {
	multipartPartIdKey := fmt.Sprintf("%s%v", cacheMultipartPartIdPrefix, data.Id)
	multipartPartUploadIdPartNumberKey := fmt.Sprintf("%s%v:%v", cacheMultipartPartUploadIdPartNumberPrefix, data.UploadId, data.PartNumber)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, multipartPartRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UploadId, data.PartNumber, data.Etag, data.Size)
	}, multipartPartIdKey, multipartPartUploadIdPartNumberKey)
	return ret, err
}

func (m *defaultMultipartPartModel) Update(ctx context.Context, newData *MultipartPart) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	multipartPartIdKey := fmt.Sprintf("%s%v", cacheMultipartPartIdPrefix, data.Id)
	multipartPartUploadIdPartNumberKey := fmt.Sprintf("%s%v:%v", cacheMultipartPartUploadIdPartNumberPrefix, data.UploadId, data.PartNumber)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, multipartPartRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UploadId, newData.PartNumber, newData.Etag, newData.Size, newData.Id)
	}, multipartPartIdKey, multipartPartUploadIdPartNumberKey)
	return err
}

func (m *defaultMultipartPartModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMultipartPartIdPrefix, primary)
}

func (m *defaultMultipartPartModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", multipartPartRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMultipartPartModel) tableName() string {
	return m.table
}
