// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	multipartUploadFieldNames          = builder.RawFieldNames(&MultipartUpload{})
	multipartUploadRows                = strings.Join(multipartUploadFieldNames, ",")
	multipartUploadRowsExpectAutoSet   = strings.Join(stringx.Remove(multipartUploadFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	multipartUploadRowsWithPlaceHolder = strings.Join(stringx.Remove(multipartUploadFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMultipartUploadIdPrefix       = "cache:multipartUpload:id:"
	cacheMultipartUploadUploadIdPrefix = "cache:multipartUpload:uploadId:"
)

type (
	multipartUploadModel interface {
		Insert(ctx context.Context, data *MultipartUpload) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MultipartUpload, error)
		FindOneByUploadId(ctx context.Context, uploadId string) (*MultipartUpload, error)
		Update(ctx context.Context, data *MultipartUpload) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMultipartUploadModel struct {
		sqlc.CachedConn
		table string
	}

	MultipartUpload struct {
		Id           uint64 `db:"id"`            // 主键ID
		UploadId     string `db:"upload_id"`     // 分片上传ID
		Bucket       string `db:"bucket"`        // 存储桶
		ObjectName   string `db:"object_name"`   // 对象名
		Size         int64  `db:"size"`          // 总大小（字节）
		ContentType  string `db:"content_type"`  // 类型
		Uploader     uint64 `db:"uploader"`      // 发起者用户ID
		Hash         string `db:"hash"`          // 哈希
		Status       int64  `db:"status"`        // 状态(0=进行中,1=完成,2=取消)
		CreateTime   int64  `db:"create_time"`   // 创建时间
		CompleteTime int64  `db:"complete_time"` // 完成时间
	}
)

func newMultipartUploadModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMultipartUploadModel {
	return &defaultMultipartUploadModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`multipart_upload`",
	}
}

func (m *defaultMultipartUploadModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	multipartUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadIdPrefix, id)
	multipartUploadUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadUploadIdPrefix, data.UploadId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, multipartUploadIdKey, multipartUploadUploadIdKey)
	return err
}

func (m *defaultMultipartUploadModel) FindOne(ctx context.Context, id uint64) (*MultipartUpload, error) {
	multipartUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadIdPrefix, id)
	var resp MultipartUpload
	err := m.QueryRowCtx(ctx, &resp, multipartUploadIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", multipartUploadRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMultipartUploadModel) FindOneByUploadId(ctx context.Context, uploadId string) (*MultipartUpload, error) {
	multipartUploadUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadUploadIdPrefix, uploadId)
	var resp MultipartUpload
	err := m.QueryRowIndexCtx(ctx, &resp, multipartUploadUploadIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `upload_id` = ? limit 1", multipartUploadRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uploadId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMultipartUploadModel) Insert(ctx context.Context, data *MultipartUpload) (sql.Result, error) {
	multipartUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadIdPrefix, data.Id)
	multipartUploadUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadUploadIdPrefix, data.UploadId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, multipartUploadRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UploadId, data.Bucket, data.ObjectName, data.Size, data.ContentType, data.Uploader, data.Hash, data.Status, data.CompleteTime)
	}, multipartUploadIdKey, multipartUploadUploadIdKey)
	return ret, err
}

func (m *defaultMultipartUploadModel) Update(ctx context.Context, newData *MultipartUpload) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	multipartUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadIdPrefix, data.Id)
	multipartUploadUploadIdKey := fmt.Sprintf("%s%v", cacheMultipartUploadUploadIdPrefix, data.UploadId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, multipartUploadRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UploadId, newData.Bucket, newData.ObjectName, newData.Size, newData.ContentType, newData.Uploader, newData.Hash, newData.Status, newData.CompleteTime, newData.Id)
	}, multipartUploadIdKey, multipartUploadUploadIdKey)
	return err
}

func (m *defaultMultipartUploadModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMultipartUploadIdPrefix, primary)
}

func (m *defaultMultipartUploadModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", multipartUploadRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMultipartUploadModel) tableName() string {
	return m.table
}
