// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: fileserver.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fileserver_CreateBucket_FullMethodName            = "/fileserver.Fileserver/CreateBucket"
	Fileserver_Upload_FullMethodName                  = "/fileserver.Fileserver/Upload"
	Fileserver_Download_FullMethodName                = "/fileserver.Fileserver/Download"
	Fileserver_InitiateMultipartUpload_FullMethodName = "/fileserver.Fileserver/InitiateMultipartUpload"
	Fileserver_UploadPart_FullMethodName              = "/fileserver.Fileserver/UploadPart"
	Fileserver_CompleteMultipartUpload_FullMethodName = "/fileserver.Fileserver/CompleteMultipartUpload"
	Fileserver_AbortMultipartUpload_FullMethodName    = "/fileserver.Fileserver/AbortMultipartUpload"
	Fileserver_GetFileMeta_FullMethodName             = "/fileserver.Fileserver/GetFileMeta"
	Fileserver_GetFileUrl_FullMethodName              = "/fileserver.Fileserver/GetFileUrl"
)

// FileserverClient is the client API for Fileserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileserverClient interface {
	CreateBucket(ctx context.Context, in *CreateBucketReq, opts ...grpc.CallOption) (*CreateBucketResp, error)
	Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error)
	Download(ctx context.Context, in *DownloadReq, opts ...grpc.CallOption) (*DownloadResp, error)
	InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadReq, opts ...grpc.CallOption) (*InitiateMultipartUploadResp, error)
	UploadPart(ctx context.Context, in *UploadPartReq, opts ...grpc.CallOption) (*UploadPartResp, error)
	CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadReq, opts ...grpc.CallOption) (*CompleteMultipartUploadResp, error)
	AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadReq, opts ...grpc.CallOption) (*AbortMultipartUploadResp, error)
	GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error)
	GetFileUrl(ctx context.Context, in *GetFileUrlReq, opts ...grpc.CallOption) (*GetFileUrlResp, error)
}

type fileserverClient struct {
	cc grpc.ClientConnInterface
}

func NewFileserverClient(cc grpc.ClientConnInterface) FileserverClient {
	return &fileserverClient{cc}
}

func (c *fileserverClient) CreateBucket(ctx context.Context, in *CreateBucketReq, opts ...grpc.CallOption) (*CreateBucketResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketResp)
	err := c.cc.Invoke(ctx, Fileserver_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResp)
	err := c.cc.Invoke(ctx, Fileserver_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) Download(ctx context.Context, in *DownloadReq, opts ...grpc.CallOption) (*DownloadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResp)
	err := c.cc.Invoke(ctx, Fileserver_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadReq, opts ...grpc.CallOption) (*InitiateMultipartUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateMultipartUploadResp)
	err := c.cc.Invoke(ctx, Fileserver_InitiateMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) UploadPart(ctx context.Context, in *UploadPartReq, opts ...grpc.CallOption) (*UploadPartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPartResp)
	err := c.cc.Invoke(ctx, Fileserver_UploadPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadReq, opts ...grpc.CallOption) (*CompleteMultipartUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMultipartUploadResp)
	err := c.cc.Invoke(ctx, Fileserver_CompleteMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadReq, opts ...grpc.CallOption) (*AbortMultipartUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortMultipartUploadResp)
	err := c.cc.Invoke(ctx, Fileserver_AbortMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetaResp)
	err := c.cc.Invoke(ctx, Fileserver_GetFileMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileserverClient) GetFileUrl(ctx context.Context, in *GetFileUrlReq, opts ...grpc.CallOption) (*GetFileUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileUrlResp)
	err := c.cc.Invoke(ctx, Fileserver_GetFileUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileserverServer is the server API for Fileserver service.
// All implementations must embed UnimplementedFileserverServer
// for forward compatibility.
type FileserverServer interface {
	CreateBucket(context.Context, *CreateBucketReq) (*CreateBucketResp, error)
	Upload(context.Context, *UploadReq) (*UploadResp, error)
	Download(context.Context, *DownloadReq) (*DownloadResp, error)
	InitiateMultipartUpload(context.Context, *InitiateMultipartUploadReq) (*InitiateMultipartUploadResp, error)
	UploadPart(context.Context, *UploadPartReq) (*UploadPartResp, error)
	CompleteMultipartUpload(context.Context, *CompleteMultipartUploadReq) (*CompleteMultipartUploadResp, error)
	AbortMultipartUpload(context.Context, *AbortMultipartUploadReq) (*AbortMultipartUploadResp, error)
	GetFileMeta(context.Context, *GetFileMetaReq) (*GetFileMetaResp, error)
	GetFileUrl(context.Context, *GetFileUrlReq) (*GetFileUrlResp, error)
	mustEmbedUnimplementedFileserverServer()
}

// UnimplementedFileserverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileserverServer struct{}

func (UnimplementedFileserverServer) CreateBucket(context.Context, *CreateBucketReq) (*CreateBucketResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedFileserverServer) Upload(context.Context, *UploadReq) (*UploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFileserverServer) Download(context.Context, *DownloadReq) (*DownloadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedFileserverServer) InitiateMultipartUpload(context.Context, *InitiateMultipartUploadReq) (*InitiateMultipartUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateMultipartUpload not implemented")
}
func (UnimplementedFileserverServer) UploadPart(context.Context, *UploadPartReq) (*UploadPartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedFileserverServer) CompleteMultipartUpload(context.Context, *CompleteMultipartUploadReq) (*CompleteMultipartUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMultipartUpload not implemented")
}
func (UnimplementedFileserverServer) AbortMultipartUpload(context.Context, *AbortMultipartUploadReq) (*AbortMultipartUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortMultipartUpload not implemented")
}
func (UnimplementedFileserverServer) GetFileMeta(context.Context, *GetFileMetaReq) (*GetFileMetaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileMeta not implemented")
}
func (UnimplementedFileserverServer) GetFileUrl(context.Context, *GetFileUrlReq) (*GetFileUrlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileUrl not implemented")
}
func (UnimplementedFileserverServer) mustEmbedUnimplementedFileserverServer() {}
func (UnimplementedFileserverServer) testEmbeddedByValue()                    {}

// UnsafeFileserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileserverServer will
// result in compilation errors.
type UnsafeFileserverServer interface {
	mustEmbedUnimplementedFileserverServer()
}

func RegisterFileserverServer(s grpc.ServiceRegistrar, srv FileserverServer) {
	// If the following call pancis, it indicates UnimplementedFileserverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fileserver_ServiceDesc, srv)
}

func _Fileserver_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).CreateBucket(ctx, req.(*CreateBucketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).Upload(ctx, req.(*UploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).Download(ctx, req.(*DownloadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_InitiateMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateMultipartUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).InitiateMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_InitiateMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).InitiateMultipartUpload(ctx, req.(*InitiateMultipartUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_UploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).UploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_UploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).UploadPart(ctx, req.(*UploadPartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_CompleteMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).CompleteMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_CompleteMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).CompleteMultipartUpload(ctx, req.(*CompleteMultipartUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_AbortMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).AbortMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_AbortMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).AbortMultipartUpload(ctx, req.(*AbortMultipartUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_GetFileMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).GetFileMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_GetFileMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).GetFileMeta(ctx, req.(*GetFileMetaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fileserver_GetFileUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileserverServer).GetFileUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fileserver_GetFileUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileserverServer).GetFileUrl(ctx, req.(*GetFileUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Fileserver_ServiceDesc is the grpc.ServiceDesc for Fileserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fileserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileserver.Fileserver",
	HandlerType: (*FileserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _Fileserver_CreateBucket_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _Fileserver_Upload_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _Fileserver_Download_Handler,
		},
		{
			MethodName: "InitiateMultipartUpload",
			Handler:    _Fileserver_InitiateMultipartUpload_Handler,
		},
		{
			MethodName: "UploadPart",
			Handler:    _Fileserver_UploadPart_Handler,
		},
		{
			MethodName: "CompleteMultipartUpload",
			Handler:    _Fileserver_CompleteMultipartUpload_Handler,
		},
		{
			MethodName: "AbortMultipartUpload",
			Handler:    _Fileserver_AbortMultipartUpload_Handler,
		},
		{
			MethodName: "GetFileMeta",
			Handler:    _Fileserver_GetFileMeta_Handler,
		},
		{
			MethodName: "GetFileUrl",
			Handler:    _Fileserver_GetFileUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fileserver.proto",
}
