// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package permissionservice

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRoleReq           = pb.AssignRoleReq
	CheckPermissionReq      = pb.CheckPermissionReq
	CheckPermissionResp     = pb.CheckPermissionResp
	CreatePermissionReq     = pb.CreatePermissionReq
	CreateRoleReq           = pb.CreateRoleReq
	CreateUserReq           = pb.CreateUserReq
	DeletePermissionReq     = pb.DeletePermissionReq
	DeleteRoleReq           = pb.DeleteRoleReq
	DeleteUserReq           = pb.DeleteUserReq
	GetPermissionReq        = pb.GetPermissionReq
	GetRoleReq              = pb.GetRoleReq
	GetUserReq              = pb.GetUserReq
	GrantPermissionReq      = pb.GrantPermissionReq
	ListPermissionsReq      = pb.ListPermissionsReq
	ListPermissionsResp     = pb.ListPermissionsResp
	ListRolePermissionsReq  = pb.ListRolePermissionsReq
	ListRolePermissionsResp = pb.ListRolePermissionsResp
	ListRolesReq            = pb.ListRolesReq
	ListRolesResp           = pb.ListRolesResp
	ListUserRolesReq        = pb.ListUserRolesReq
	ListUserRolesResp       = pb.ListUserRolesResp
	ListUsersReq            = pb.ListUsersReq
	ListUsersResp           = pb.ListUsersResp
	LoginReq                = pb.LoginReq
	LoginResp               = pb.LoginResp
	LogoutReq               = pb.LogoutReq
	LogoutResp              = pb.LogoutResp
	Permission              = pb.Permission
	PermissionResp          = pb.PermissionResp
	RefreshTokenReq         = pb.RefreshTokenReq
	RevokePermissionReq     = pb.RevokePermissionReq
	RevokeRoleReq           = pb.RevokeRoleReq
	Role                    = pb.Role
	RoleResp                = pb.RoleResp
	UpdatePermissionReq     = pb.UpdatePermissionReq
	UpdateRoleReq           = pb.UpdateRoleReq
	UpdateUserReq           = pb.UpdateUserReq
	User                    = pb.User
	UserResp                = pb.UserResp
	VerifyTokenReq          = pb.VerifyTokenReq
	VerifyTokenResp         = pb.VerifyTokenResp

	PermissionService interface {
		CreatePermission(ctx context.Context, in *CreatePermissionReq, opts ...grpc.CallOption) (*PermissionResp, error)
		GetPermission(ctx context.Context, in *GetPermissionReq, opts ...grpc.CallOption) (*PermissionResp, error)
		UpdatePermission(ctx context.Context, in *UpdatePermissionReq, opts ...grpc.CallOption) (*PermissionResp, error)
		DeletePermission(ctx context.Context, in *DeletePermissionReq, opts ...grpc.CallOption) (*LogoutResp, error)
		ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error)
		CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
	}

	defaultPermissionService struct {
		cli zrpc.Client
	}
)

func NewPermissionService(cli zrpc.Client) PermissionService {
	return &defaultPermissionService{
		cli: cli,
	}
}

func (m *defaultPermissionService) CreatePermission(ctx context.Context, in *CreatePermissionReq, opts ...grpc.CallOption) (*PermissionResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.CreatePermission(ctx, in, opts...)
}

func (m *defaultPermissionService) GetPermission(ctx context.Context, in *GetPermissionReq, opts ...grpc.CallOption) (*PermissionResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.GetPermission(ctx, in, opts...)
}

func (m *defaultPermissionService) UpdatePermission(ctx context.Context, in *UpdatePermissionReq, opts ...grpc.CallOption) (*PermissionResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdatePermission(ctx, in, opts...)
}

func (m *defaultPermissionService) DeletePermission(ctx context.Context, in *DeletePermissionReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.DeletePermission(ctx, in, opts...)
}

func (m *defaultPermissionService) ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.ListPermissions(ctx, in, opts...)
}

func (m *defaultPermissionService) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}
