// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package healthservice

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRoleReq           = pb.AssignRoleReq
	CheckPermissionReq      = pb.CheckPermissionReq
	CheckPermissionResp     = pb.CheckPermissionResp
	CreatePermissionReq     = pb.CreatePermissionReq
	CreateRoleReq           = pb.CreateRoleReq
	CreateUserReq           = pb.CreateUserReq
	DeletePermissionReq     = pb.DeletePermissionReq
	DeleteRoleReq           = pb.DeleteRoleReq
	DeleteUserReq           = pb.DeleteUserReq
	GetPermissionReq        = pb.GetPermissionReq
	GetRoleReq              = pb.GetRoleReq
	GetUserReq              = pb.GetUserReq
	GrantPermissionReq      = pb.GrantPermissionReq
	HealthCheckReq          = pb.HealthCheckReq
	HealthCheckResp         = pb.HealthCheckResp
	ListPermissionsReq      = pb.ListPermissionsReq
	ListPermissionsResp     = pb.ListPermissionsResp
	ListRolePermissionsReq  = pb.ListRolePermissionsReq
	ListRolePermissionsResp = pb.ListRolePermissionsResp
	ListRolesReq            = pb.ListRolesReq
	ListRolesResp           = pb.ListRolesResp
	ListUserRolesReq        = pb.ListUserRolesReq
	ListUserRolesResp       = pb.ListUserRolesResp
	ListUsersReq            = pb.ListUsersReq
	ListUsersResp           = pb.ListUsersResp
	LoginReq                = pb.LoginReq
	LoginResp               = pb.LoginResp
	LogoutReq               = pb.LogoutReq
	LogoutResp              = pb.LogoutResp
	Permission              = pb.Permission
	PermissionResp          = pb.PermissionResp
	RefreshTokenReq         = pb.RefreshTokenReq
	RevokePermissionReq     = pb.RevokePermissionReq
	RevokeRoleReq           = pb.RevokeRoleReq
	Role                    = pb.Role
	RoleResp                = pb.RoleResp
	UpdatePermissionReq     = pb.UpdatePermissionReq
	UpdateRoleReq           = pb.UpdateRoleReq
	UpdateUserReq           = pb.UpdateUserReq
	User                    = pb.User
	UserResp                = pb.UserResp
	VerifyTokenReq          = pb.VerifyTokenReq
	VerifyTokenResp         = pb.VerifyTokenResp

	HealthService interface {
		HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
	}

	defaultHealthService struct {
		cli zrpc.Client
	}
)

func NewHealthService(cli zrpc.Client) HealthService {
	return &defaultHealthService{
		cli: cli,
	}
}

func (m *defaultHealthService) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	client := pb.NewHealthServiceClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}
