// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/internal/logic/userservice"
	"github.com/cy77cc/go-microstack/usercenter/rpc/internal/svc"
	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) CreateUser(ctx context.Context, in *pb.CreateUserReq) (*pb.UserResp, error) {
	l := userservicelogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.UserResp, error) {
	l := userservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServiceServer) UpdateUser(ctx context.Context, in *pb.UpdateUserReq) (*pb.UserResp, error) {
	l := userservicelogic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServiceServer) DeleteUser(ctx context.Context, in *pb.DeleteUserReq) (*pb.LogoutResp, error) {
	l := userservicelogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *UserServiceServer) ListUsers(ctx context.Context, in *pb.ListUsersReq) (*pb.ListUsersResp, error) {
	l := userservicelogic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *UserServiceServer) AssignRoleToUser(ctx context.Context, in *pb.AssignRoleReq) (*pb.LogoutResp, error) {
	l := userservicelogic.NewAssignRoleToUserLogic(ctx, s.svcCtx)
	return l.AssignRoleToUser(in)
}

func (s *UserServiceServer) RevokeRoleFromUser(ctx context.Context, in *pb.RevokeRoleReq) (*pb.LogoutResp, error) {
	l := userservicelogic.NewRevokeRoleFromUserLogic(ctx, s.svcCtx)
	return l.RevokeRoleFromUser(in)
}

func (s *UserServiceServer) ListUserRoles(ctx context.Context, in *pb.ListUserRolesReq) (*pb.ListUserRolesResp, error) {
	l := userservicelogic.NewListUserRolesLogic(ctx, s.svcCtx)
	return l.ListUserRoles(in)
}
