// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AssignRoleBody struct {
	RoleIds []uint64 `json:"roleIds"`
}

type CheckPermissionReq struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

type CheckPermissionResp struct {
	Allowed bool `json:"allowed"`
}

type GetHealthResp struct {
	Status string `json:"status"`
}

type GrantPermissionBody struct {
	PermissionIds []uint64 `json:"permissionIds"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LogoutReq struct {
	RefreshToken string `json:"refreshToken"`
}

type PermissionCreateReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Type        int32  `json:"type"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Description string `json:"description"`
}

type PermissionListReq struct {
	Page     int32 `query:"page"`
	PageSize int32 `query:"pageSize"`
}

type PermissionListResp struct {
	Total int64            `json:"total"`
	List  []PermissionResp `json:"list"`
}

type PermissionResp struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Type        int32  `json:"type"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
	CreateTime  int64  `json:"createTime"`
	UpdateTime  int64  `json:"updateTime"`
}

type PermissionUpdateReq struct {
	Id          uint64 `path:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Type        int32  `json:"type"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RevokePermissionBody struct {
	PermissionIds []uint64 `json:"permissionIds"`
}

type RevokeRoleBody struct {
	RoleIds []uint64 `json:"roleIds"`
}

type RoleCreateReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

type RoleListReq struct {
	Page     int32 `query:"page"`
	PageSize int32 `query:"pageSize"`
}

type RoleListResp struct {
	Total int64      `json:"total"`
	List  []RoleResp `json:"list"`
}

type RoleResp struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
	CreateTime  int64  `json:"createTime"`
	UpdateTime  int64  `json:"updateTime"`
}

type RoleUpdateReq struct {
	Id          uint64 `path:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int32  `json:"status"`
}

type TokenResp struct {
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	Expires      int64    `json:"expires"`
	Uid          uint64   `json:"uid"`
	Roles        []string `json:"roles"`
}

type UserCreateReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
}

type UserListReq struct {
	Page     int32  `query:"page"`
	PageSize int32  `query:"pageSize"`
	Query    string `query:"query"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	List  []UserResp `json:"list"`
}

type UserResp struct {
	Id            uint64 `json:"id"`
	Username      string `json:"username"`
	Email         string `json:"email"`
	Phone         string `json:"phone"`
	Avatar        string `json:"avatar"`
	Status        int32  `json:"status"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
	LastLoginTime int64  `json:"lastLoginTime"`
}

type UserUpdateReq struct {
	Id     uint64 `path:"id"`
	Email  string `json:"email"`
	Phone  string `json:"phone"`
	Avatar string `json:"avatar"`
	Status int32  `json:"status"`
}
