// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: fileserver.proto

package fileserver

import (
	"context"

	"github.com/cy77cc/go-microstack/fileserver/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AbortMultipartUploadReq     = pb.AbortMultipartUploadReq
	AbortMultipartUploadResp    = pb.AbortMultipartUploadResp
	CompleteMultipartUploadReq  = pb.CompleteMultipartUploadReq
	CompleteMultipartUploadResp = pb.CompleteMultipartUploadResp
	CompletedPart               = pb.CompletedPart
	CreateBucketReq             = pb.CreateBucketReq
	CreateBucketResp            = pb.CreateBucketResp
	DownloadReq                 = pb.DownloadReq
	DownloadResp                = pb.DownloadResp
	FileMeta                    = pb.FileMeta
	GetFileMetaReq              = pb.GetFileMetaReq
	GetFileMetaResp             = pb.GetFileMetaResp
	GetFileUrlReq               = pb.GetFileUrlReq
	GetFileUrlResp              = pb.GetFileUrlResp
	InitiateMultipartUploadReq  = pb.InitiateMultipartUploadReq
	InitiateMultipartUploadResp = pb.InitiateMultipartUploadResp
	UploadPartReq               = pb.UploadPartReq
	UploadPartResp              = pb.UploadPartResp
	UploadReq                   = pb.UploadReq
	UploadResp                  = pb.UploadResp

	Fileserver interface {
		CreateBucket(ctx context.Context, in *CreateBucketReq, opts ...grpc.CallOption) (*CreateBucketResp, error)
		Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error)
		Download(ctx context.Context, in *DownloadReq, opts ...grpc.CallOption) (*DownloadResp, error)
		InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadReq, opts ...grpc.CallOption) (*InitiateMultipartUploadResp, error)
		UploadPart(ctx context.Context, in *UploadPartReq, opts ...grpc.CallOption) (*UploadPartResp, error)
		CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadReq, opts ...grpc.CallOption) (*CompleteMultipartUploadResp, error)
		AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadReq, opts ...grpc.CallOption) (*AbortMultipartUploadResp, error)
		GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error)
		GetFileUrl(ctx context.Context, in *GetFileUrlReq, opts ...grpc.CallOption) (*GetFileUrlResp, error)
	}

	defaultFileserver struct {
		cli zrpc.Client
	}
)

func NewFileserver(cli zrpc.Client) Fileserver {
	return &defaultFileserver{
		cli: cli,
	}
}

func (m *defaultFileserver) CreateBucket(ctx context.Context, in *CreateBucketReq, opts ...grpc.CallOption) (*CreateBucketResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.CreateBucket(ctx, in, opts...)
}

func (m *defaultFileserver) Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.Upload(ctx, in, opts...)
}

func (m *defaultFileserver) Download(ctx context.Context, in *DownloadReq, opts ...grpc.CallOption) (*DownloadResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.Download(ctx, in, opts...)
}

func (m *defaultFileserver) InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadReq, opts ...grpc.CallOption) (*InitiateMultipartUploadResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.InitiateMultipartUpload(ctx, in, opts...)
}

func (m *defaultFileserver) UploadPart(ctx context.Context, in *UploadPartReq, opts ...grpc.CallOption) (*UploadPartResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.UploadPart(ctx, in, opts...)
}

func (m *defaultFileserver) CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadReq, opts ...grpc.CallOption) (*CompleteMultipartUploadResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.CompleteMultipartUpload(ctx, in, opts...)
}

func (m *defaultFileserver) AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadReq, opts ...grpc.CallOption) (*AbortMultipartUploadResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.AbortMultipartUpload(ctx, in, opts...)
}

func (m *defaultFileserver) GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.GetFileMeta(ctx, in, opts...)
}

func (m *defaultFileserver) GetFileUrl(ctx context.Context, in *GetFileUrlReq, opts ...grpc.CallOption) (*GetFileUrlResp, error) {
	client := pb.NewFileserverClient(m.cli.Conn())
	return client.GetFileUrl(ctx, in, opts...)
}
