// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AbortMultipartReq struct {
	UploadId string `path:"uploadId"` // 分片上传ID
}

type BucketReq struct {
	Bucket      string `json:"bucket"`      // Bucket名称
	StorageType int32  `json:"storageType"` // 存储类型
}

type BucketResp struct {
	Bucket string `json:"bucket"` // Bucket名称
}

type CompleteMultipartReq struct {
	UploadId string          `path:"uploadId"` // 分片上传ID
	Parts    []CompletedPart `json:"parts"`    // 所有分片信息
}

type CompleteMultipartResp struct {
	FileId string `json:"fileId"` // 文件ID
	Bucket string `json:"bucket"` // 存储桶
	Key    string `json:"key"`    // 文件路径
	Size   int64  `json:"size"`   // 最终大小
}

type CompletedPart struct {
	PartNumber uint32 `json:"partNumber"` // 分片序号
	ETag       string `json:"eTag"`       // ETag
}

type FileMetaResp struct {
	FileId      string `json:"fileId"`      // 文件ID
	FileName    string `json:"fileName"`    // 文件名
	Bucket      string `json:"bucket"`      // 存储桶
	Key         string `json:"key"`         // 路径
	Size        int64  `json:"size"`        // 大小
	ContentType string `json:"contentType"` // MIME类型
	Uploader    uint64 `json:"uploader"`    // 上传者ID
	UploadTime  int64  `json:"uploadTime"`  // 上传时间
	Hash        string `json:"hash"`        // Hash值
	Status      int64  `json:"status"`      // 状态
}

type HealthResp struct {
	Status string `json:"status"` // 状态
}

type InitiateMultipartReq struct {
	Bucket      string `json:"bucket"`      // 存储桶
	Key         string `json:"key"`         // 文件路径
	Hash        string `json:"hash"`        // 文件Hash
	Size        int64  `json:"size"`        // 总大小
	ContentType string `json:"contentType"` // MIME类型
}

type InitiateMultipartResp struct {
	UploadId string `json:"uploadId"` // 分片上传ID
}

type PresignResp struct {
	Url    string `json:"url"`    // 访问URL
	Expire int64  `json:"expire"` // 过期时间戳
}

type UploadFileReq struct {
	Bucket      string `form:"bucket"`      // 存储桶名称
	Key         string `form:"key"`         // 文件路径/名称
	Hash        string `form:"hash"`        // 文件Hash
	Size        int64  `form:"size"`        // 文件大小
	ContentType string `form:"contentType"` // MIME类型
}

type UploadFileResp struct {
	FileId string `json:"fileId"` // 文件ID
	Bucket string `json:"bucket"` // 存储桶
	Key    string `json:"key"`    // 文件路径
	Size   int64  `json:"size"`   // 大小
	ETag   string `json:"eTag"`   // ETag
}

type UploadPartReq struct {
	UploadId   string `path:"uploadId"`   // 分片上传ID
	PartNumber uint32 `path:"partNumber"` // 分片序号
}

type UploadPartResp struct {
	ETag       string `json:"eTag"`       // 分片ETag
	PartNumber uint32 `json:"partNumber"` // 分片序号
}
