// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AbortMultipartReq struct {
	UploadId string `path:"uploadId"`
}

type BucketReq struct {
	Bucket      string `json:"bucket"`
	StorageType int32  `json:"storageType"`
}

type BucketResp struct {
	Bucket string `json:"bucket"`
}

type CompleteMultipartReq struct {
	UploadId string          `path:"uploadId"`
	Parts    []CompletedPart `json:"parts"`
}

type CompleteMultipartResp struct {
	FileId string `json:"fileId"`
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
	Size   int64  `json:"size"`
}

type CompletedPart struct {
	PartNumber uint32 `json:"partNumber"`
	ETag       string `json:"eTag"`
}

type FileMetaResp struct {
	FileId      string `json:"fileId"`
	FileName    string `json:"fileName"`
	Bucket      string `json:"bucket"`
	Key         string `json:"key"`
	Size        int64  `json:"size"`
	ContentType string `json:"contentType"`
	Uploader    uint64 `json:"uploader"`
	UploadTime  int64  `json:"uploadTime"`
	Hash        string `json:"hash"`
	Status      int64  `json:"status"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type InitiateMultipartReq struct {
	Bucket      string `json:"bucket"`
	Key         string `json:"key"`
	Hash        string `json:"hash"`
	Size        int64  `json:"size"`
	ContentType string `json:"contentType"`
}

type InitiateMultipartResp struct {
	UploadId string `json:"uploadId"`
}

type PresignResp struct {
	Url    string `json:"url"`
	Expire int64  `json:"expire"`
}

type UploadFileReq struct {
	Bucket      string `form:"bucket"`
	Key         string `form:"key"`
	Hash        string `form:"hash"`
	Size        int64  `form:"size"`
	ContentType string `form:"contentType"`
}

type UploadFileResp struct {
	FileId string `json:"fileId"`
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
	Size   int64  `json:"size"`
	ETag   string `json:"eTag"`
}

type UploadPartReq struct {
	UploadId   string `path:"uploadId"`
	PartNumber uint32 `path:"partNumber"`
}

type UploadPartResp struct {
	ETag       string `json:"eTag"`
	PartNumber uint32 `json:"partNumber"`
}
