// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	auth "github.com/cy77cc/go-microstack/usercenter/api/internal/handler/auth"
	permissions "github.com/cy77cc/go-microstack/usercenter/api/internal/handler/permissions"
	rbac "github.com/cy77cc/go-microstack/usercenter/api/internal/handler/rbac"
	roles "github.com/cy77cc/go-microstack/usercenter/api/internal/handler/roles"
	users "github.com/cy77cc/go-microstack/usercenter/api/internal/handler/users"
	"github.com/cy77cc/go-microstack/usercenter/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: GetHealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/refresh",
					Handler: auth.RefreshHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/permissions",
					Handler: permissions.CreatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/permissions",
					Handler: permissions.ListPermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/permissions/:id",
					Handler: permissions.GetPermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/permissions/:id",
					Handler: permissions.UpdatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/permissions/:id",
					Handler: permissions.DeletePermissionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/rbac/check",
					Handler: rbac.CheckPermissionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: roles.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: roles.ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roles/:id",
					Handler: roles.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/roles/:id",
					Handler: roles.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/roles/:id",
					Handler: roles.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/roles/:id/permissions",
					Handler: roles.GrantPermissionToRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/roles/:id/permissions",
					Handler: roles.RevokePermissionFromRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roles/:id/permissions",
					Handler: roles.ListRolePermissionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: users.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: users.ListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:id",
					Handler: users.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users/:id",
					Handler: users.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/:id",
					Handler: users.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/:id/roles",
					Handler: users.AssignRoleToUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/:id/roles",
					Handler: users.RevokeRoleFromUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:id/roles",
					Handler: users.ListUserRolesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
