// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: usercenter.proto

package authservice

import (
	"context"

	"github.com/cy77cc/go-microstack/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRoleReq           = pb.AssignRoleReq
	CheckPermissionReq      = pb.CheckPermissionReq
	CheckPermissionResp     = pb.CheckPermissionResp
	CreatePermissionReq     = pb.CreatePermissionReq
	CreateRoleReq           = pb.CreateRoleReq
	CreateUserReq           = pb.CreateUserReq
	DeletePermissionReq     = pb.DeletePermissionReq
	DeleteRoleReq           = pb.DeleteRoleReq
	DeleteUserReq           = pb.DeleteUserReq
	GetPermissionReq        = pb.GetPermissionReq
	GetRoleReq              = pb.GetRoleReq
	GetUserReq              = pb.GetUserReq
	GrantPermissionReq      = pb.GrantPermissionReq
	ListPermissionsReq      = pb.ListPermissionsReq
	ListPermissionsResp     = pb.ListPermissionsResp
	ListRolePermissionsReq  = pb.ListRolePermissionsReq
	ListRolePermissionsResp = pb.ListRolePermissionsResp
	ListRolesReq            = pb.ListRolesReq
	ListRolesResp           = pb.ListRolesResp
	ListUserRolesReq        = pb.ListUserRolesReq
	ListUserRolesResp       = pb.ListUserRolesResp
	ListUsersReq            = pb.ListUsersReq
	ListUsersResp           = pb.ListUsersResp
	LoginReq                = pb.LoginReq
	LoginResp               = pb.LoginResp
	LogoutReq               = pb.LogoutReq
	LogoutResp              = pb.LogoutResp
	Permission              = pb.Permission
	PermissionResp          = pb.PermissionResp
	RefreshTokenReq         = pb.RefreshTokenReq
	RevokePermissionReq     = pb.RevokePermissionReq
	RevokeRoleReq           = pb.RevokeRoleReq
	Role                    = pb.Role
	RoleResp                = pb.RoleResp
	UpdatePermissionReq     = pb.UpdatePermissionReq
	UpdateRoleReq           = pb.UpdateRoleReq
	UpdateUserReq           = pb.UpdateUserReq
	User                    = pb.User
	UserResp                = pb.UserResp
	VerifyTokenReq          = pb.VerifyTokenReq
	VerifyTokenResp         = pb.VerifyTokenResp

	AuthService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultAuthService) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}
